### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by marslanm** [hockeybro12/FakeNews_Inference_Operators#3]
Hi @hockeybro12 

Could you please share **requirements.txt** to install all the packages required for running the code.

**Comment by hockeybro12** [comment]
Hi @marslanm 

Sorry for the delay. I don't have a requirements.txt, but I don't think the list of packages is very long. You should be able to find most of the imports in the top of the `GNN_model.py` file. The main packages (aside from the standard python packages like scikit-learn) are probably `dgl` and `PyTorch`.

**Comment by marslanm** [comment]
Thanks, I found these packages appropriate for this code.

conda create --name env_name  python=3.8

pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu111/torch_stable.html

pip install dgl-cu111

conda install -c pytorch faiss-gpu

pip install pandas==1.5.0

pip install tldextract==3.4.0

pip install joblib==1.2.0

pip install pytorch-transformers==1.2.0

pip install scikit-learn==1.1.3

**Comment by hockeybro12** [comment]
Thanks @marslanm  for updating!
